# Generated by Django 4.2.7 on 2024-06-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_cart',
        ),
    ]
