# Generated by Django 4.2.7 on 2024-06-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_cart_cart_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture_item',
            name='item_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furniture_item',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='furniture_item',
            name='item_type',
            field=models.CharField(choices=[('sofa', 'Sofa'), ('table', 'Table'), ('footstool', 'Footstool')], max_length=50),
        ),
    ]
