# Generated by Django 4.2.7 on 2024-06-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_furniture_item_item_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture_item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
