# Generated by Django 4.2.7 on 2024-06-12 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0004_furniture_item_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture_item',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='furniture_item',
            name='item_rating',
        ),
        migrations.RemoveField(
            model_name='furniture_item',
            name='num_reviews',
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('num_reviews', models.ImageField(default=0, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.furniture_item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
