# Generated by Django 4.2.7 on 2024-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_remove_furniture_item_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture_item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='furniture_item',
            name='item_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='furniture_item',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
