# Generated by Django 4.2.7 on 2024-06-12 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseapp', '0006_furniture_item_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture_item',
            name='rated_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
